# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-09 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('author_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BookAuthors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylibrary.Authors')),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylibrary.Book')),
            ],
        ),
        migrations.CreateModel(
            name='BookLoans',
            fields=[
                ('loan_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('date_out', models.DateField()),
                ('due_date', models.DateField()),
                ('date_in', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('card_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('ssn', models.CharField(max_length=9)),
                ('bname', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_amt', models.FloatField()),
                ('paid', models.BooleanField()),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylibrary.BookLoans')),
            ],
        ),
        migrations.AddField(
            model_name='bookloans',
            name='card_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylibrary.Borrower'),
        ),
        migrations.AddField(
            model_name='bookloans',
            name='isbn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylibrary.Book'),
        ),
    ]
