# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-10 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='author_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
