# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0003_auto_20170709_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
