# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0005_auto_20170715_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='card_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='ssn',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
