# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 06:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0006_auto_20170715_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookloans',
            name='date_out',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bookloans',
            name='due_date',
            field=models.DateField(default=datetime.date(2017, 7, 30)),
        ),
        migrations.AlterField(
            model_name='bookloans',
            name='loan_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
