# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0008_auto_20170716_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookloans',
            name='date_in',
            field=models.DateField(blank=True, null=True),
        ),
    ]
