# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0011_auto_20170716_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookloans',
            name='isbn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylibrary.Book'),
        ),
        migrations.AlterUniqueTogether(
            name='bookloans',
            unique_together=set([('isbn', 'date_out')]),
        ),
    ]
