# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 04:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0012_auto_20170716_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fines',
            name='id',
        ),
        migrations.AlterField(
            model_name='bookloans',
            name='card_id',
            field=models.ForeignKey(error_messages={'unique': 'This email has already been registered.'}, on_delete=django.db.models.deletion.CASCADE, to='mylibrary.Borrower'),
        ),
        migrations.AlterField(
            model_name='bookloans',
            name='isbn',
            field=models.ForeignKey(error_messages={'unique': 'This email has already been registered.'}, on_delete=django.db.models.deletion.CASCADE, to='mylibrary.Book'),
        ),
        migrations.AlterField(
            model_name='fines',
            name='fine_amt',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='fines',
            name='loan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mylibrary.BookLoans'),
        ),
        migrations.AlterField(
            model_name='fines',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
