# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 00:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0013_auto_20170716_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookloans',
            name='due_date',
            field=models.DateField(default=datetime.date(2017, 8, 1)),
        ),
        migrations.AlterField(
            model_name='fines',
            name='loan_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mylibrary.BookLoans'),
        ),
        migrations.AlterUniqueTogether(
            name='bookloans',
            unique_together=set([]),
        ),
    ]
